# Generated by Django 4.2.6 on 2023-10-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatowner_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
