# Generated by Django 4.2.6 on 2023-10-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatowner',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
