swagger: '2.0'
info:
  title: LeLuChat API
  description: API for LeLuChat Engine
  version: v1
host:
schemes:
- http
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
  Basic:
    type: basic
security:
- Basic: []
- Token: []
paths:
  /accounts/change-password:
    post:
      operationId: accounts_change-password_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - accounts
    parameters: []
  /accounts/login:
    post:
      operationId: accounts_login_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - accounts
    parameters: []
  /accounts/logout:
    post:
      operationId: accounts_logout_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - accounts
    parameters: []
  /accounts/password_reset/:
    post:
      operationId: accounts_password_reset_create
      summary: An Api View which provides a method to request a password reset token
        based on an e-mail address
      description: Sends a signal reset_password_token_created when a reset token
        was created
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Email'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Email'
      tags:
      - accounts
    parameters: []
  /accounts/password_reset/confirm/:
    post:
      operationId: accounts_password_reset_confirm_create
      description: An Api View which provides a method to reset a password based on
        a unique token
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/PasswordToken'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordToken'
      tags:
      - accounts
    parameters: []
  /accounts/password_reset/validate_token/:
    post:
      operationId: accounts_password_reset_validate_token_create
      description: An Api View which provides a method to verify that a token is valid
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/ResetToken'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/ResetToken'
      tags:
      - accounts
    parameters: []
  /accounts/register:
    post:
      operationId: accounts_register_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - accounts
    parameters: []
  /accounts/token-refresh/:
    post:
      operationId: accounts_token-refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenRefresh'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenRefresh'
      tags:
      - accounts
    parameters: []
  /accounts/users/:
    get:
      operationId: accounts_users_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - accounts
    parameters: []
  /engine/chats/{uid}/messages/:
    get:
      operationId: engine_chats_messages_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - engine
    parameters:
    - name: uid
      in: path
      required: true
      type: string
  /engine/rooms/:
    get:
      operationId: engine_rooms_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - engine
    post:
      operationId: engine_rooms_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - engine
    parameters: []
  /engine/rooms/{uid}/:
    get:
      operationId: engine_rooms_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - engine
    put:
      operationId: engine_rooms_update
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - engine
    delete:
      operationId: engine_rooms_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - engine
    parameters:
    - name: uid
      in: path
      required: true
      type: string
  /engine/rooms/{uid}/chats/:
    get:
      operationId: engine_rooms_chats_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - engine
    post:
      operationId: engine_rooms_chats_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - engine
    parameters:
    - name: uid
      in: path
      required: true
      type: string
  /engine/rooms/{uid}/members:
    post:
      operationId: engine_rooms_members_create
      description: ''
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - engine
    patch:
      operationId: engine_rooms_members_partial_update
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - engine
    parameters:
    - name: uid
      in: path
      required: true
      type: string
definitions:
  Email:
    required:
    - email
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
  PasswordToken:
    required:
    - password
    - token
    type: object
    properties:
      password:
        title: Password
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
  ResetToken:
    required:
    - token
    type: object
    properties:
      token:
        title: Token
        type: string
        minLength: 1
  TokenRefresh:
    required:
    - refresh
    type: object
    properties:
      refresh:
        title: Refresh
        type: string
        minLength: 1
      access:
        title: Access
        type: string
        readOnly: true
        minLength: 1
